sonar.projectKey=my-todo-list
sonar.projectName=My To-Do List (React Native)
sonar.projectVersion=1.0

# Le decimos que busque en la raíz, pero solo los archivos de código
sonar.sources=.
sonar.inclusions=**/*.ts,**/*.tsx,**/*.js,**/*.jsx

# Exclusiones críticas para proyectos Expo/React Native
sonar.exclusions=node_modules/**,.expo/**,android/**,ios/**,assets/**,**/*.test.ts,**/*.test.tsx,babel.config.js,eslint.config.js

sonar.sourceEncoding=UTF-8

sonar.tests=.
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info